name: C++ CI

on: 
  push:
    branches:
    - master
    - develop

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: test
      run: ls -la
    - name: configure
      run: cd build && cmake ..
    - name: build
      run: cd build && cmake --build . --target install
