name: C++ CI

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    runs-on: ${{matrix.os}}
    
    steps:
      - uses: actions/checkout@master

      - name: configure
        run: cd build && cmake ..

      - name: build
        run: cd build && cmake --build . --target install

      - name: test
        run: ./build/bin/tests
